import jsPDF from 'jspdf';
import type { Valuation } from '@shared/schema';

export interface PDFGenerationData {
  valuation: Valuation;
  industryData: {
    industry: string;
    multiple: number;
    description: string;
    factors: string[];
  };
}

export function generateValuationPDF(data: PDFGenerationData): jsPDF {
  const pdf = new jsPDF();
  const { valuation, industryData } = data;
  
  // Header
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Business Valuation Report', 20, 30);
  
  // Subtitle
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Generated on ${new Date().toLocaleDateString()}`, 20, 40);
  
  // Business Information
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Business Information', 20, 60);
  
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  let yPos = 75;
  
  pdf.text(`Business Name: ${valuation.businessName}`, 20, yPos);
  yPos += 10;
  pdf.text(`Industry: ${industryData.description}`, 20, yPos);
  yPos += 10;
  pdf.text(`Location: ${valuation.location}`, 20, yPos);
  yPos += 10;
  pdf.text(`Years in Business: ${valuation.yearsInBusiness}`, 20, yPos);
  yPos += 15;
  
  // Financial Summary
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Financial Summary', 20, yPos);
  yPos += 15;
  
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Annual Revenue: $${parseFloat(valuation.annualRevenue).toLocaleString()}`, 20, yPos);
  yPos += 10;
  pdf.text(`Seller's Discretionary Earnings (SDE): $${parseFloat(valuation.sde).toLocaleString()}`, 20, yPos);
  yPos += 10;
  if (valuation.addBacks && parseFloat(valuation.addBacks) > 0) {
    pdf.text(`Add-backs: $${parseFloat(valuation.addBacks).toLocaleString()}`, 20, yPos);
    yPos += 10;
  }
  yPos += 10;
  
  // Valuation Results
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Valuation Results', 20, yPos);
  yPos += 15;
  
  // Highlight box for valuation range
  pdf.setFillColor(240, 248, 255);
  pdf.rect(15, yPos - 5, 180, 25, 'F');
  
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Estimated Business Value Range:', 20, yPos + 5);
  
  pdf.setFontSize(16);
  pdf.setTextColor(0, 100, 200);
  pdf.text(`$${parseFloat(valuation.valuationLow).toLocaleString()} - $${parseFloat(valuation.valuationHigh).toLocaleString()}`, 20, yPos + 15);
  
  pdf.setTextColor(0, 0, 0);
  yPos += 35;
  
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Industry Multiple Used: ${parseFloat(valuation.industryMultiple).toFixed(2)}x SDE`, 20, yPos);
  yPos += 15;
  
  // Business Assessment
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Business Assessment', 20, yPos);
  yPos += 15;
  
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Owner Involvement: ${valuation.ownerInvolvement}`, 20, yPos);
  yPos += 10;
  pdf.text(`Growth Trend: ${valuation.growthTrend}`, 20, yPos);
  yPos += 10;
  
  if (valuation.majorRisks) {
    pdf.text('Major Risks:', 20, yPos);
    yPos += 8;
    const risks = pdf.splitTextToSize(valuation.majorRisks, 170);
    pdf.text(risks, 25, yPos);
    yPos += risks.length * 6 + 10;
  }
  
  // Industry Factors
  if (yPos > 250) {
    pdf.addPage();
    yPos = 30;
  }
  
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Industry-Specific Factors', 20, yPos);
  yPos += 15;
  
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  industryData.factors.forEach((factor: string) => {
    pdf.text(`• ${factor}`, 25, yPos);
    yPos += 8;
  });
  
  yPos += 15;
  
  // Disclaimer
  if (yPos > 250) {
    pdf.addPage();
    yPos = 30;
  }
  
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Important Disclaimer', 20, yPos);
  yPos += 15;
  
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  const disclaimer = `This valuation is for informational purposes only and should not be considered a formal business appraisal. The estimate is based on industry multiples and the information provided. Actual business value may vary significantly based on market conditions, buyer preferences, due diligence findings, and other factors not captured in this analysis. We recommend consulting with a qualified business appraiser or financial advisor for transactions or formal valuations.`;
  
  const disclaimerLines = pdf.splitTextToSize(disclaimer, 170);
  pdf.text(disclaimerLines, 20, yPos);
  
  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(128, 128, 128);
  pdf.text('Generated by ValuationGenie', 20, 280);
  pdf.text(`Report ID: ${valuation.id}`, 140, 280);
  
  return pdf;
}

export function downloadPDF(pdf: jsPDF, filename: string) {
  pdf.save(filename);
}

export function getPDFBlob(pdf: jsPDF): Blob {
  return pdf.output('blob');
}